# Generated by Django 4.2 on 2024-03-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_id_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=12, verbose_name='number'),
        ),
    ]
