# Generated by Django 4.2 on 2024-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_id_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(null=True, verbose_name='address'),
        ),
    ]
